Tried to change to Enum
There's a bug with this error message:
 File "joint_inference.py", line 107, in <module>
    print(plot_joint_inference(data))
  File "joint_inference.py", line 64, in plot_joint_inference
    verb_categories, epsilon, delta = joint_inference(data, 600)
  File "joint_inference.py", line 43, in joint_inference
    timelogepsilon = MH(data, verb_categories[i], delta[i], epsilon[i], gammas, 10, Var.EPSILON)
  File "/Users/shalineemaitra/Documents/GitHub/noise-filter-tidy/MH.py", line 68, in MH
    result = propose_and_accept(data, verb_categories, delta, epsilon, gammas, MHvar, p_MHvar, flag)
  File "/Users/shalineemaitra/Documents/GitHub/noise-filter-tidy/propose_and_accept.py", line 79, in propose_and_accept
    p_var_prime = pdf_theta_one_verb(data, delta, epsilon, var_prime, gammas)
  File "/Users/shalineemaitra/Documents/GitHub/noise-filter-tidy/pdf_theta.py", line 46, in pdf_theta_one_verb
    n1 = range(n+1)
TypeError: can only concatenate list (not "int") to list